### ISSUE TITLE
No support for snap themes

### ISSUE THREAD

**Issue by jakejarrett** [jaszhix/electron-gtk-theme#1]
Not sure if this will be a problem in Ubuntu 18.10, but the `communitheme` / yaru theme currently on 18.04 is installed as a snap which will require the [following change to be put in place](https://github.com/jakejarrett/node-gtk-theme/commit/8b7d50249b54336f9d46a527758fa3f2113af942)

**Comment by jaszhix** [comment]
Hi @jakejarrett, I think I got it working, though I had to fake the environment a little because I'm using Cinnamon. Can you [verify](https://github.com/jaszhix/SystemDelight/releases/tag/v0.0.2) if the change is working? Thanks.

**Comment by jakejarrett** [comment]
Hey, Thanks, that worked 👍
