### ISSUE TITLE
Update logic of GTK Button layout

### ISSUE THREAD

**Issue by jakejarrett** [jaszhix/electron-gtk-theme#2]
Small change needed here;
I botched the implementation and it won't work **as expected** (believe it was working, but upon implementation of a real-world use case, it was not working as expected)

The following needs to be changed;
https://github.com/jaszhix/electron-gtk-theme/blob/01c6df1e4b67587cabfdafdc4961c2a46a93dc5b/getGTKTheme.js#L111

The change can be found here-
https://github.com/jakejarrett/node-gtk-theme/commit/ade0126ecc2a5d23b3a1d79bee5808002e6af6aa

Should be updated to the following;
```js
 if (decorationLayout.indexOf(':') === decorationLayout.length - 1) {
```

**Comment by jaszhix** [comment]
Thanks for letting me know! I'll be able to update this tonight.
